# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MATRIX: "[{\"repo\":\"doitsujin/dxvk\",\"workflow\":\"artifacts.yml\",\"branch\":\"master\"}]"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: echo "version_matrix=${{ env.MATRIX }}" >> $GITHUB_OUTPUT
    outputs:
      version_matrix: ${{ steps.set-matrix.outputs.version_matrix }}

  # This workflow contains a single job called "download"
  download:
    needs: build-matrix
    strategy:
      matrix:
        components: ${{ fromJson(needs.build-matrix.outputs.version_matrix) }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download artifact
        id: download-artifact
        uses: koplo199/action-download-artifact@1.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          # Optional, workflow file name or ID
          # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
          workflow: ${{ matrix.components.workflow }}
          # Optional, will use the specified branch. Defaults to all branches
          branch: ${{ matrix.components.branch }}
          # Optional, defaults to current repo
          repo: ${{ matrix.components.repo }}
          # Optional, check the workflow run to whether it has an artifact
          # then will get the last available artifact from the previous workflow
          # default false, just try to download from the last one
          check_artifacts:  true

      - name : Print sha
        run: echo ${{ steps.download-artifact.outputs.head_sha }}

  # This workflow contains a single job called "build"
  upload:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Display structure of downloaded files
        run: ls -la