# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  COMPONENTS: '[
            {"repo" : "doitsujin/dxvk"                , "workflow": "artifacts.yml", "branch": "master", "name-prefix": "dxvk"        , "Category": "dxvk" , "Sub-category": ""},
            {"repo" : "HansKristian-Work/vkd3d-proton", "workflow": "artifacts.yml", "branch": "master", "name-prefix": "vkd3d-proton", "Category": "vkd3d", "Sub-category": ""}, 
            {"repo" : "koplo199/components"           , "workflow": "blank.yml"    , "branch": "main"  , "name-prefix": ""            , "Category": ""     , "Sub-category": ""},
          ]'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: echo 'version_matrix=${{ env.COMPONENTS }}' >> $GITHUB_OUTPUT
    outputs:
      version_matrix: ${{ steps.set-matrix.outputs.version_matrix }}

  # This workflow contains a single job called "download"
  download:
    needs: build-matrix
    strategy:
      matrix:
        components: ${{ fromJson(needs.build-matrix.outputs.version_matrix) }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: true
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download artifact
        id: download-artifact
        uses: koplo199/action-download-artifact@1.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          # Optional, workflow file name or ID
          # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
          workflow: ${{ matrix.components.workflow }}
          # Optional, will use the specified branch. Defaults to all branches
          branch: ${{ matrix.components.branch }}
          # Optional, defaults to current repo
          repo: ${{ matrix.components.repo }}
          # Optional, check the workflow run to whether it has an artifact
          # then will get the last available artifact from the previous workflow
          # default false, just try to download from the last one
          check_artifacts:  true
          # Optional, a directory where to extract artifact(s), defaults to the current directory
          path: ${{ matrix.components.name-prefix }}

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: "our-repository"

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.components.repo }}
          path: "other-repository"
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          pip3 install yq

      - name : Print sha
        run: |
          ls -la dxvk
          ls -la our-repository
          ls -la other-repository
          cd other-repository
          ls
          git status
          git merge-base --is-ancestor ${{ steps.download-artifact.outputs.head_sha }} 67d03aabd0c9b57d00e18d0aca8aca60e27f2ea9; echo "$?"
          git merge-base --is-ancestor ${{ steps.download-artifact.outputs.head_sha }} master; echo "$?"
          echo ${{ steps.download-artifact.outputs.head_sha }}

  # This workflow contains a single job called "build"
  upload:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Display structure of downloaded files
        run: ls -la