# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
  PR_BRANCH: CI-${{ github.ref_name }}

concurrency: 
  # Github Actions does not support ${{ env.PR_BRANCH }} as group name...
  group: CI-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: "bottle-components-repository"
      
      - name: Create or reset ${{ env.PR_BRANCH }}
        working-directory: "bottle-components-repository"
        run: |
          git checkout -B ${{ env.PR_BRANCH }}
          git push -f --set-upstream origin ${{ env.PR_BRANCH }}

  download:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        components: [
            {repo : "doitsujin/dxvk"                  , workflow: "artifacts.yml"          , branch: "master", name-prefix: "dxvk-"        , version-prefix: "v"        , Category: "dxvk"       , Sub-category: ""      , yaml-file: "14_dxvk.yml"         },
            {repo : "HansKristian-Work/vkd3d-proton"  , workflow: "artifacts.yml"          , branch: "master", name-prefix: "vkd3d-proton-", version-prefix: "v"        , Category: "vkd3d"      , Sub-category: ""      , yaml-file: "13_vkd3d-proton.yml" },
            {repo : "bottlesdevs/wine"                , workflow: ""                       , branch: "soda"  , name-prefix: "soda-"        , version-prefix: "soda-"    , Category: "runners"    , Sub-category: "wine"  , yaml-file: "3_soda.yml"          },
            {repo : "bottlesdevs/wine"                , workflow: ""                       , branch: "caffe" , name-prefix: "caffe-"       , version-prefix: "caffe-"   , Category: "runners"    , Sub-category: "wine"  , yaml-file: "4_caffe.yml"         },
            {repo : "GloriousEggroll/wine-ge-custom"  , workflow: ""                       , branch: "master", name-prefix: "wine-"        , version-prefix: ""         , Category: "runners"    , Sub-category: "wine"  , yaml-file: "5_wine-GE-Proton.yml"},
            {repo : "GloriousEggroll/proton-ge-custom", workflow: ""                       , branch: "master", name-prefix: "GE-Proton"    , version-prefix: "GE-Proton", Category: "runners"    , Sub-category: "proton", yaml-file: "10_GE-Proton.yml"    },
            {repo : "ishitatsuyuki/LatencyFleX"       , workflow: "artifact.yml"           , branch: "master", name-prefix: "latencyflex-" , version-prefix: ""         , Category: "latencyflex", Sub-category: ""      , yaml-file: "17_latencyflex.yml"  },
            {repo : "jp7677/dxvk-nvapi"               , workflow: "artifacts.yml"          , branch: "master", name-prefix: "dxvk-nvapi-"  , version-prefix: ""         , Category: "nvapi"      , Sub-category: ""      , yaml-file: "16_dxvk-nvapi.yml"   },
            {repo : "Sporif/dxvk-async"               , workflow: ""                       , branch: "master", name-prefix: "dxvk-async-"  , version-prefix: ""         , Category: "dxvk"       , Sub-category: ""      , yaml-file: "15_dxvk-async.yml"   },
          ]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check for new release
        id: check-release
        uses: koplo199/actions-download-asset@1.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repo: ${{ matrix.components.repo }}
          version: latest
          file: /${{ matrix.components.name-prefix }}.*[0-9\-_.]+\.tar.*/
          prefix: ${{ matrix.components.version-prefix }}

      - uses: actions/checkout@v3
        with:
          path: "bottle-components-repository"
          ref: ${{ env.PR_BRANCH }}

      - uses: actions/checkout@v3
        with:
          repository: bottlesdevs/tools
          path: "tools"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip zstd
          pip3 install yq

      - name: Update component stable input_file entry
        id: update-release-yml
        working-directory: "bottle-components-repository"
        run: |
          res=$(./input_files/update_yml_entries.sh "${{ matrix.components.name-prefix }}" "${{ steps.check-release.outputs.version }}" "${{ matrix.components.Category }}" "${{ matrix.components.Sub-category }}" "stable" "" "$(pwd)/input_files/${{ matrix.components.yaml-file }}" "${{ fromJSON(steps.check-release.outputs.asset).created_at }}")
          exit_code="$?"
          if [ "$res" != "Updated." ] || [ "$exit_code" -ne 0 ]; then
            echo "updated=false" >> $GITHUB_OUTPUT
            echo $res
            if [ "$res" != "Already up to date." ]; then
              exit 1
            fi
          else
            echo "updated=true" >> $GITHUB_OUTPUT
            release_archive=${{ steps.check-release.outputs.out }}
            if [[ $release_archive == *".tar.gz" ]] || [[ $release_archive == *".tar.xz" ]] || [[ $release_archive == *".tar.bz2" ]]; then
              repo=${{ matrix.components.repo }}
              python "${{ github.workspace }}/tools/MaintainersHelpers/component-generator.py" "components" "${repo%/*}" "${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}" "${repo%/*}" "stable" "${{ fromJSON(steps.check-release.outputs.asset).browser_download_url }}"
              mv "${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}.yml" "${{ matrix.components.Category }}/${{ matrix.components.Sub-category }}"
            else
              case $release_archive in
                *".tar.zst")
                  tar --use-compress-program=unzstd -xvf $release_archive
                  ;;
                *".zip")
                  unzip $release_archive
                  ;;
              esac
              tar -C "${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}" -zcvf "${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}.tar.gz" $(ls ${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }})
              echo "upload_file=$(pwd)/${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}.tar.gz" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Upload release
        id: release
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
        if: steps.update-release-yml.outputs.upload_file != ''
        with:
          tag_name: "${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}"
          files: |
            ${{ steps.update-release-yml.outputs.upload_file }}
      
      - name : Generate release yml file
        if: steps.update-release-yml.outputs.upload_file != ''
        working-directory: "bottle-components-repository"
        run: |
          repo=${{ matrix.components.repo }}
          python "${{ github.workspace }}/tools/MaintainersHelpers/component-generator.py" "components" "${repo%/*}" "${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}" "${repo%/*}" "stable" "${{ fromJSON(steps.release.outputs.assets)[0].browser_download_url }}"
          mv "${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}.yml" "${{ matrix.components.Category }}/${{ matrix.components.Sub-category }}"

      - name: Check for new artifact
        id: download-artifact
        if: matrix.components.workflow != '' && steps.update-release-yml.outputs.updated == 'false'
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          # Optional, workflow file name or ID
          # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
          workflow: ${{ matrix.components.workflow }}
          # Optional, will use the specified branch. Defaults to all branches
          branch: ${{ matrix.components.branch }}
          # Optional, defaults to current repo
          repo: ${{ matrix.components.repo }}
          # Optional, check the workflow run to whether it has an artifact
          # then will get the last available artifact from the previous workflow
          # default false, just try to download from the last one
          check_artifacts:  true
          # Optional, a directory where to extract artifact(s), defaults to the current directory
          path: artifact

      - name: Update component unstable input_file entry
        id: update-artifact-yml
        if: matrix.components.workflow != '' && steps.update-release-yml.outputs.updated == 'false'
        working-directory: "bottle-components-repository"
        run: |
          res=$(./input_files/update_yml_entries.sh "${{ matrix.components.name-prefix }}" "${{ steps.check-release.outputs.version }}" "${{ matrix.components.Category }}" "${{ matrix.components.Sub-category }}" "unstable" "${{ fromJSON(steps.download-artifact.outputs.artifacts)[0].workflow_run.head_sha }}" "$(pwd)/input_files/${{ matrix.components.yaml-file }}" "${{ fromJSON(steps.download-artifact.outputs.artifacts)[0].created_at }}")
          exit_code="$?"
          if [ "$res" != "Updated." ] || [ "$exit_code" -ne 0 ]; then
            echo "updated=false" >> $GITHUB_OUTPUT
            echo $res
            if [ "$res" != "Already up to date." ]; then
              exit 1
            fi
          else
            echo "updated=true" >> $GITHUB_OUTPUT
            folder=$(find "${{ github.workspace }}/artifact" -name "${{ matrix.components.name-prefix }}*")
            if [[ "${{ matrix.components.name-prefix }}" == "dxvk"* ]]; then
              rm -rf $folder/usr
            fi
            tar -C "$folder" -zcvf "${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}-${{ fromJSON(steps.download-artifact.outputs.artifacts)[0].workflow_run.head_sha }}.tar.gz" $(ls "$folder")
            echo "upload_file=$(pwd)/${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}-${{ fromJSON(steps.download-artifact.outputs.artifacts)[0].workflow_run.head_sha }}.tar.gz" >> $GITHUB_OUTPUT
          fi

      - name: Upload artifact
        id: artifact
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
        if: steps.update-artifact-yml.outputs.upload_file != ''
        with:
          tag_name: "${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}-${{ fromJSON(steps.download-artifact.outputs.artifacts)[0].workflow_run.head_sha }}"
          files: |
            ${{ steps.update-artifact-yml.outputs.upload_file }}

      - name : Generate artifact yml file
        if: steps.update-artifact-yml.outputs.upload_file != ''
        working-directory: "bottle-components-repository"
        run: |
          repo=${{ matrix.components.repo }}
          commit_sha1=${{ fromJSON(steps.download-artifact.outputs.artifacts)[0].workflow_run.head_sha }}
          python "${{ github.workspace }}/tools/MaintainersHelpers/component-generator.py" "components" "${repo%/*}" "${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}-1-${commit_sha1::7}" "${repo%/*}" "unstable" "${{ fromJSON(steps.artifact.outputs.assets)[0].browser_download_url }}"
          mv "${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}-1-${commit_sha1::7}.yml" "${{ matrix.components.Category }}/${{ matrix.components.Sub-category }}"

      - name : Commit changes
        if: steps.update-release-yml.outputs.updated == 'true' || steps.update-artifact-yml.outputs.updated == 'true'
        working-directory: "bottle-components-repository"
        shell: bash {0}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add "${{ matrix.components.Category }}/${{ matrix.components.Sub-category }}/*.yml" "input_files/${{ matrix.components.yaml-file }}"
          git pull
          git commit -m "Apply ${{ matrix.components.yaml-file }} changes"
          git push
          success=$?
          until [ $success -eq 0 ]; do
            git pull --rebase;
            git push
            success=$?
          done

  end:
    needs: download
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: "bottle-components-repository"
          ref: ${{ env.PR_BRANCH }}
          fetch-depth: 0

      - name: Fetch and checkout ${{ github.ref_name }}
        working-directory: "bottle-components-repository"
        run: |
          git fetch origin ${{ github.ref_name }}
          git checkout ${{ github.ref_name }}
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git merge ${{ env.PR_BRANCH }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          path: "bottle-components-repository"
          branch: pr-${{ env.PR_BRANCH }}
          delete-branch: true
