name: CI

on:
  push:
    branches:
      # Branches containing '/' won't be matched
      - '*'
  schedule:
    # Check for update every day at 07:07
    - cron:  '7 7 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PR_BRANCH: ci/${{ github.ref_name }}

concurrency: 
  # Github Actions does not support ${{ env.PR_BRANCH }} as group name...
  group: ci/${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: "bottle-components-repository"
          ref: ${{ github.ref_name }}
      
      - name: Create or reset ${{ env.PR_BRANCH }}
        working-directory: "bottle-components-repository"
        run: |
          git checkout -B ${{ env.PR_BRANCH }}
          git push -f --set-upstream origin ${{ env.PR_BRANCH }}

  download:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        components: [
            {repo : "doitsujin/dxvk"                  , workflow: "artifacts.yml"          , branch: "master", name-prefix: "dxvk-"        , version-prefix: "v"        , Category: "dxvk"       , Sub-category: ""      , yaml-file: "14-dxvk.yml"         },
            {repo : "HansKristian-Work/vkd3d-proton"  , workflow: "artifacts.yml"          , branch: "master", name-prefix: "vkd3d-proton-", version-prefix: "v"        , Category: "vkd3d"      , Sub-category: ""      , yaml-file: "13-vkd3d-proton.yml" },
            {repo : "bottlesdevs/wine"                , workflow: ""                       , branch: "soda"  , name-prefix: "soda-"        , version-prefix: "soda-"    , Category: "runners"    , Sub-category: "wine"  , yaml-file: "3-soda.yml"          },
            {repo : "bottlesdevs/wine"                , workflow: ""                       , branch: "caffe" , name-prefix: "caffe-"       , version-prefix: "caffe-"   , Category: "runners"    , Sub-category: "wine"  , yaml-file: "4-caffe.yml"         },
            {repo : "GloriousEggroll/wine-ge-custom"  , workflow: ""                       , branch: "master", name-prefix: "wine-"        , version-prefix: ""         , Category: "runners"    , Sub-category: "wine"  , yaml-file: "5-wine-GE-Proton.yml"},
            {repo : "GloriousEggroll/proton-ge-custom", workflow: ""                       , branch: "master", name-prefix: "GE-Proton"    , version-prefix: "GE-Proton", Category: "runners"    , Sub-category: "proton", yaml-file: "10-GE-Proton.yml"    },
            {repo : "ishitatsuyuki/LatencyFleX"       , workflow: "artifact.yml"           , branch: "master", name-prefix: "latencyflex-" , version-prefix: ""         , Category: "latencyflex", Sub-category: ""      , yaml-file: "17-latencyflex.yml"  },
            {repo : "jp7677/dxvk-nvapi"               , workflow: "artifacts.yml"          , branch: "master", name-prefix: "dxvk-nvapi-"  , version-prefix: ""         , Category: "nvapi"      , Sub-category: ""      , yaml-file: "16-dxvk-nvapi.yml"   },
            {repo : "Sporif/dxvk-async"               , workflow: ""                       , branch: "master", name-prefix: "dxvk-async-"  , version-prefix: ""         , Category: "dxvk"       , Sub-category: ""      , yaml-file: "15-dxvk-async.yml"   },
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Check for new release
        id: check-release
        uses: koplo199/actions-download-asset@1.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repo: ${{ matrix.components.repo }}
          version: latest
          file: /${{ matrix.components.name-prefix }}.*[0-9\-_.]+\.tar.*/
          prefix: ${{ matrix.components.version-prefix }}

      - uses: actions/checkout@v3
        with:
          path: "bottle-components-repository"
          ref: ${{ env.PR_BRANCH }}

      - uses: actions/checkout@v3
        with:
          repository: bottlesdevs/tools
          path: "tools"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip zstd
          pip3 install yq

      - name: Define release environment variables
        run: |
          lowercase_component_name=$(echo "${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}" | tr "[:upper:]" "[:lower:]")
          echo "COMPONENT_NAME=$lowercase_component_name" >> $GITHUB_ENV
          echo "COMPONENT_CHANNEL=stable" >> $GITHUB_ENV
          echo "COMPONENT_CREATED_AT=${{ fromJSON(steps.check-release.outputs.asset).created_at }}" >> $GITHUB_ENV

      - name: Update component stable input_file entry
        id: update-release-yml
        working-directory: "bottle-components-repository"
        run: |
          res=$(./input_files/update_yml_entries.sh "$(echo ${{ matrix.components.name-prefix }} | tr '[:upper:]' '[:lower:]')" "${{ env.COMPONENT_NAME }}" "${{ matrix.components.Category }}" "${{ matrix.components.Sub-category }}" "${{ env.COMPONENT_CHANNEL }}" "$(pwd)/input_files/${{ matrix.components.yaml-file }}" "${{ env.COMPONENT_CREATED_AT }}")
          exit_code="$?"
          if [ "$res" != "Updated." ] || [ "$exit_code" -ne 0 ]; then
            echo $res
            if [ "$res" != "Already up to date." ]; then
              exit 1
            fi
          else
            echo "updated=true" >> $GITHUB_OUTPUT
            release_archive=${{ steps.check-release.outputs.out }}
            if [[ $release_archive == *".tar.zst" ]]; then
              tar --use-compress-program=unzstd -xvf $release_archive
              tar -C "${{ env.COMPONENT_NAME }}" -zcvf "${{ env.COMPONENT_NAME }}.tar.gz" $(ls ${{ env.COMPONENT_NAME }})
              echo "upload_file=$(pwd)/${{ env.COMPONENT_NAME }}.tar.gz" >> $GITHUB_OUTPUT
            fi
          fi
      
      - name: Check for new artifact
        id: download-artifact
        if: matrix.components.workflow != '' && steps.update-release-yml.outputs.updated != 'true'
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: ${{ matrix.components.workflow }}
          branch: ${{ matrix.components.branch }}
          repo: ${{ matrix.components.repo }}
          check_artifacts:  true
          if_no_artifact_found: warn
          path: artifact

      - name: Define artifact environment variables
        if: matrix.components.workflow != '' && steps.update-release-yml.outputs.updated != 'true' && steps.download-artifact.outputs.found_artifact == 'true'
        run: |
          commit_sha1="${{ fromJSON(steps.download-artifact.outputs.artifacts)[0].workflow_run.head_sha }}"
          lowercase_component_name=$(echo "${{ matrix.components.name-prefix }}${{ steps.check-release.outputs.version }}-1-${commit_sha1::7}" | tr "[:upper:]" "[:lower:]")
          echo "COMPONENT_NAME=$lowercase_component_name" >> $GITHUB_ENV
          echo "COMPONENT_CHANNEL=unstable" >> $GITHUB_ENV
          echo "COMPONENT_CREATED_AT=${{ fromJSON(steps.download-artifact.outputs.artifacts)[0].created_at }}" >> $GITHUB_ENV

      - name: Update component unstable input_file entry
        id: update-artifact-yml
        if: matrix.components.workflow != '' && steps.update-release-yml.outputs.updated != 'true' && steps.download-artifact.outputs.found_artifact == 'true'
        working-directory: "bottle-components-repository"
        run: |
          res=$(./input_files/update_yml_entries.sh "$(echo ${{ matrix.components.name-prefix }} | tr '[:upper:]' '[:lower:]')" "${{ env.COMPONENT_NAME }}" "${{ matrix.components.Category }}" "${{ matrix.components.Sub-category }}" "${{ env.COMPONENT_CHANNEL }}" "$(pwd)/input_files/${{ matrix.components.yaml-file }}" "${{ env.COMPONENT_CREATED_AT }}")
          exit_code="$?"
          if [ "$res" != "Updated." ] || [ "$exit_code" -ne 0 ]; then
            echo $res
            if [ "$res" != "Already up to date." ]; then
              exit 1
            fi
          else
            echo "updated=true" >> $GITHUB_OUTPUT
            folder=$(find "${{ github.workspace }}/artifact" -name "${{ matrix.components.name-prefix }}*")
            if [[ "${{ matrix.components.name-prefix }}" == "dxvk"* ]]; then
              rm -rf $folder/usr
            fi
            tar -C "$folder" -zcvf "${{ env.COMPONENT_NAME }}.tar.gz" $(ls "$folder")
            echo "upload_file=$(pwd)/${{ env.COMPONENT_NAME }}.tar.gz" >> $GITHUB_OUTPUT
          fi

      - name: Upload component
        id: component
        uses: koplo199/action-gh-release@1.0
        if: steps.update-artifact-yml.outputs.upload_file != '' || steps.update-release-yml.outputs.upload_file != ''
        with:
          tag_name: "${{ env.COMPONENT_NAME }}"
          files: |
            ${{ steps.update-artifact-yml.outputs.upload_file }}
            ${{ steps.update-release-yml.outputs.upload_file }}

      - name : Generate appropriate yml file
        if: steps.update-release-yml.outputs.updated == 'true' || steps.update-artifact-yml.outputs.updated == 'true'
        working-directory: "bottle-components-repository"
        run: |
          repo=${{ matrix.components.repo }}
          if [ "${{ steps.component.outputs.assets }}" != "" ]; then
            url="${{ steps.component.outputs.assets && fromJSON(steps.component.outputs.assets)[0].browser_download_url }}"
          else
            url="${{ fromJSON(steps.check-release.outputs.asset).browser_download_url }}"
          fi
          python "${{ github.workspace }}/tools/MaintainersHelpers/component-generator.py" "components" "${repo%/*}" "${{ env.COMPONENT_NAME }}" "${repo%/*}" "${{ env.COMPONENT_CHANNEL }}" "$url"
          mv "${{ env.COMPONENT_NAME }}.yml" "${{ matrix.components.Category }}/${{ matrix.components.Sub-category }}"

      - name : Commit changes
        if: steps.update-release-yml.outputs.updated == 'true' || steps.update-artifact-yml.outputs.updated == 'true'
        working-directory: "bottle-components-repository"
        timeout-minutes: 10
        shell: bash {0}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add "${{ matrix.components.Category }}/${{ matrix.components.Sub-category }}/*.yml" "input_files/${{ matrix.components.yaml-file }}"
          git pull
          git commit -m "Update ${{ matrix.components.yaml-file }}"
          git push
          success=$?
          until [ $success -eq 0 ]; do
            git pull --rebase;
            git push
            success=$?
          done

  end:
    needs: download
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: "bottle-components-repository"
          ref: ${{ env.PR_BRANCH }}
          fetch-depth: 0

      - name: Generate index.yml
        working-directory: "bottle-components-repository"
        run: |
          git checkout ${{ github.ref_name }}
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git merge ${{ env.PR_BRANCH }}
          ./generate_index.sh
          git add index.yml
          git commit -m "Generate index.yml"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          path: "bottle-components-repository"
          branch: pr/${{ env.PR_BRANCH }}
          delete-branch: true
          title: "Update available :tada:"
          body: One or more components have been updated!
